<script>
    //try() ,catch ,finally will be useful for solving problems like exiting from the program due to an error
    //we use the catch block to catch that error and runs the prog smoothly without terminating it

    console.log(5/pizza);
//
    try{
        console.log(5/pizza);
    }
    catch(error){
        console.log("NaN..divisor should be a number");
    }
    finally{
        console.log("this prog comes to an end");
    }


</script>